version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: backend
    volumes:
      - ..:/var/www/html
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydatabase
    depends_on:
      - db
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ..:/var/www/html
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
